//! Build inputs the binary cannot carry as Rust source: the application
//! manifest, and the Catalogue's compiled `.mo` files.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use polib::po_file::POParseOptions;

fn main() {
    embed_manifest();
    compile_catalogues();
}

/// Embeds `app.manifest` into the exe via the MSVC linker, with no extra crate
/// dependency. The linker still contributes its own default trustInfo
/// (asInvoker), so `app.manifest` deliberately does not declare one — two
/// trustInfo blocks would be a merge conflict.
fn embed_manifest() {
    let manifest = manifest_dir().join("app.manifest");
    println!("cargo:rerun-if-changed=app.manifest");
    println!("cargo:rustc-link-arg-bins=/MANIFEST:EMBED");
    println!(
        "cargo:rustc-link-arg-bins=/MANIFESTINPUT:{}",
        manifest.display()
    );
}

/// Compiles every `i18n/<code>.po` into `OUT_DIR/<code>.mo` and writes the table
/// `catalog.rs` includes (spec §11). Everything a new language needs from the
/// build is this enumeration: drop `xx.po` in and the `.mo`, the table and
/// `available_translations` follow. (Naming the language to the rest of the
/// application is a separate hand edit — see `pathmaster_core::language`.)
///
/// `polib` writes what it is given, so the two exclusions `msgfmt` performs are
/// performed here: an untranslated message would answer with an *empty string*
/// where a miss should have fallen back to the English msgid, and a fuzzy one —
/// gettext's "guessed after the source changed" — must read as missing, which is
/// what the completeness gate assumes when it reads the `.po` rather than the `.mo`.
fn compile_catalogues() {
    let i18n = manifest_dir().join("i18n");
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    println!("cargo:rerun-if-changed=i18n");

    let mut codes: Vec<String> = Vec::new();
    for entry in std::fs::read_dir(&i18n).expect("the i18n directory") {
        let path = entry.expect("an i18n directory entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("po") {
            continue;
        }
        let code = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("a language code")
            .to_owned();
        println!("cargo:rerun-if-changed=i18n/{code}.po");
        compile_catalogue(&path, &out_dir.join(format!("{code}.mo")));
        codes.push(code);
    }
    assert!(
        !codes.is_empty(),
        "no catalogue found in {}",
        i18n.display()
    );
    codes.sort();

    let mut table = String::from(
        "// Generated by build.rs from i18n/*.po — one row per language.\n\
         static CATALOGUES: &[(&str, &[u8])] = &[\n",
    );
    for code in &codes {
        writeln!(
            table,
            "    ({code:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{code}.mo\"))),"
        )
        .expect("writing to a String");
    }
    table.push_str("];\n");
    std::fs::write(out_dir.join("catalogues.rs"), table).expect("writing the catalogue table");
}

fn compile_catalogue(po: &Path, mo: &Path) {
    let options = POParseOptions {
        translated_only: true,
        ..POParseOptions::new()
    };
    let mut catalog = polib::po_file::parse_with_option(po, &options)
        .unwrap_or_else(|e| panic!("{} does not parse: {e}", po.display()));

    let fuzzy: Vec<(String, Option<String>)> = catalog
        .messages()
        .filter(|message| message.is_fuzzy())
        .map(|message| {
            (
                message.msgid().to_owned(),
                message.msgid_plural().ok().map(str::to_owned),
            )
        })
        .collect();
    for (msgid, plural) in fuzzy {
        catalog.delete_message(None, &msgid, plural.as_deref());
    }

    polib::mo_file::write(&catalog, mo)
        .unwrap_or_else(|e| panic!("{} could not be written: {e}", mo.display()));
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}
